#Name:       ?
Category:    .
#URI:        ?
#ActualVers: ?#[]
#Platforms:  ?#[]
#Suitable:   ?#{Universal|Desktop|Server|NoExpand}
#Hidden:     Yes
List:        .#{2|1|0}
#FSTEC_lic:  ?#[]
#MOD_lic:    ?#[]
#FSC_lic:    ?#[]
#MinComReg:  ?
#Install:    ?
#Tags:       ?#[]
#Brief:      ?
#Footnote:   ?
